//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Crossover> Crossovers { get; set; }
        public virtual DbSet<Descendant> Descendants { get; set; }
        public virtual DbSet<PairFormation> PairFormations { get; set; }
        public virtual DbSet<Population> Populations { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<SelectPoint> SelectPoints { get; set; }
    }
}
